### ISSUE TITLE
Access forbidden during nominal pipeline execution of harvest on Mars2020 archive

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#124]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I’ve been running Harvest on our Mars 2020 holdings. It was going swimmingly, but today I saw that it entered a loop. It would log that it’s processing the same ~50 products, and then an error would spit out after a batch saying the following:

Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)]

### 🕵️ Expected behavior

I expected to harvest the data, as usual

### 📜 To Reproduce

See attached log.

[logs.txt](https://github.com/NASA-PDS/harvest/files/11818670/logs.txt)

### 🖥 Environment Info

Linux environment

### 📚 Version of Software Used

v3.7.6

### 🩺 Test Data / Additional context

Should be executed against IMG's Registry

**Comment by alexdunnjpl** [comment]
@jordanpadams this is almost certainly the result of usage of the ES disk allocation reaching a cutoff threshold.

When exactly were these errors encountered?

**Comment by alexdunnjpl** [comment]
Closing as not-a-bug, further discussion in #125
