### ISSUE TITLE
As a user, I want to ingest data products with labels having `.lblx` file extension

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#130]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator

### 💪 Motivation

...so that I can load data from labels that use both XML or LBLX file extensions

### Acceptance Criteria

**Given** a bundle/directory using lblx file extensions for labels
**When I perform** harvest on that target dir
**Then I expect** the lblx files will be loaded

### ⚙️ Engineering Details

- [ ] Add ability to configure in config file
- [ ] Add command line argument (takes precedence over config file)
- [ ] Update [Registry](https://github.com/NASA-PDS/registry) documentation to note this flag now exists

**Comment by al-niessner** [comment]
@jordanpadams 

Can I get an example of this please? I can find a couple of places where .xml is used as a limiter, but maybe just removing that so that any extension could be used may be more beneficial than adding .xml and lbxl and ...

**Comment by jordanpadams** [comment]
@al-niessner you can just take any bundle/collection we have and change all the files from `.xml` to `.lblx`

**Comment by jordanpadams** [comment]
@al-niessner reopening this ticket. see my comment here: https://github.com/NASA-PDS/harvest/pull/137#discussion_r1370702013

**Comment by jordanpadams** [comment]
@al-niessner @tloubrieu-jpl I added a checklist to the Engineering Details in the original ticket above
