### ISSUE TITLE
Harvest times out while processing some PDS products

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/harvest#132]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did process some large bundles, I noticed various files timeout. I reprocessed the bundles again, and some timeouts occur again, but progress is made. 

### 🕵️ Expected behavior

I expected the bundle to process successfully.

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Operating System: VM - Windows Server 2019, 64bit, 2 core 3.59 GHz, 16GB RAM
...

### 📚 Version of Software Used

Harvest version: 3.7.6
Build time: 2023-03-30T19:36:02Z

### 🩺 Test Data / Additional context

[urn-nasa-pds-mex_marsis_optim_timeouts.txt](https://github.com/NASA-PDS/harvest/files/12717114/urn-nasa-pds-mex_marsis_optim_timeouts.txt)
[urn-nasa-pds-lro_diviner_derived1_timeouts.txt](https://github.com/NASA-PDS/harvest/files/12717117/urn-nasa-pds-lro_diviner_derived1_timeouts.txt)

Let me know if there is a simple timeout parameter to set in the config files of harvest. 

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@scholes-ds thanks for filing this ticket. We actually have this tracked here: https://github.com/NASA-PDS/harvest/issues/125. If you have any additional notes on the timeout, feel free to comment there.
