### ISSUE TITLE
As a user, I want the default archive_status for loaded products to be configurable

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#135]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data operators in the discipline nodes.

### 💪 Motivation

...so that I can skip the staged status (when metadata comes from a validated database) and make the product directly available to the public.

### Acceptance Criteria

**Given** a bundle
**When I perform** harvest on it with an option `--archive-status archived`
**Then I expect** the products of this bundles to all have the archive-status `archived`.

**Given** a bundle
**When I perform** harvest on it **without** option `--archive-status archived`
**Then I expect** the products of this bundles to all have the archive-status `staged`.

**Comment by tloubrieu-jpl** [comment]
@tariqksoliman 

For now the archive_status is hardcoded in the code (see https://github.com/NASA-PDS/registry-common/blob/main/src/main/java/gov/nasa/pds/registry/common/meta/BasicMetadataExtractor.java#L61) so it is not possible as for now to change the value to 'archived' at run time.

I created this ticket to add that action in our queue. The next step will be to schedule this development and for the short term you should run `registry-manager set-archive-status` as a separated step.

See https://nasa-pds.github.io/registry/user/update_status.html

Sorry about that

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Two items with this ticket.

1. It will need to have all of the same checking of the status CLI option checking of registry-mgr set-archive-status. Do you want to move that CLI stuff from registry-mgr to registry-common, make harvest depend on registry-mgr, do a gut-n-paste of options like in the past for expedience today?
2. Can they set it to any state? At some point there had been discussion about using this state to understand the data ingestion. Staged was given to us by user. Some other state for we did our checks to make sure all looked good. Some other state that it was ready to be made public at users request etc. Is this idea forgotten or junked?

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner,

For question 1, to me, that would make most sense to have the archive-status enumeration and anything else needed in registry-common.
For question 2, I don't know... I would say yes, they can set the initial value with as much liberty as they set it with set-archive-status. I don't believe the idea of stage is junked and that would remain the default behavior, but there might be edge cases where the user would like to directly set the archive status as 'archived', if the validation is done upstream the registry for example.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Given that the same code will have to move as we already conflict with, going to wait for NASA-PDS/registry-mgr#73 to be merged.

If any user can set the status to anything, then that simply junks the concept of us using to understand its ingestion status with respect to doing internal checking.

One other question I had as I was starting to do the CLI switch `--set-archive-status`. Is that for all or just latest. Do we need three of them: all, latest, all but latest?

**Comment by jordanpadams** [comment]
📆 06/2024 status: In work. On schedule. Blocked by https://github.com/NASA-PDS/registry-mgr/pull/73

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Is this the same as NASA-PDS/registry-mgr#69? Do we want 2 ways to do the same thing that might produce different results? Should we close this ticket and say NASA-PDS/registry-mgr#69 satisfies this or vice versa?

**Comment by jordanpadams** [comment]
@al-niessner These are actually 2 separate requirements. This is a new feature to be able to set an `archive_status` upon initial load of the data. This removes the step to run registry-mgr to set the archive status.
