### ISSUE TITLE
harvest does not seem to be properly harvesting or catching come collection updates

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/harvest#145]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run harvest on GEO's Diviner EDR & RDR bundles, the collection updates are not being captured.
These are PDS3 data sets that are updated to be PDS4 bundles. The collections are down two directory levels from the bundle xml file. 

### 🕵️ Expected behavior

I expected harvest to pick up the updates that were recently made by GEO Node's data archivists to these bundles

### 📜 To Reproduce

Run harvest on these two bundles:
https://pds-geosciences.wustl.edu/lro/lro-l-dlre-2-edr-v1/
https://pds-geosciences.wustl.edu/lro/lro-l-dlre-4-rdr-v1/

Output from harvest:

harvest -c e:/opt/configs22/bundle-lro_divinerEDRRDR.xml -l e:/opt/configs22/2023-12-14lro_divinerEDRRDR.log
[SUMMARY] Reading configuration from e:\opt\configs22\bundle-lro_divinerEDRRDR.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: https://search-geo-prod-6iz6lwiw6luyffpsq52ndsrtbu.us-west-2.es.amazonaws.com:443, index: registry
[INFO] Connecting to Elasticsearch
[INFO] Loading PDS to ES data type mapping from e:\opt\harvest-3.9.0\elastic\data-dic-types.cfg
[INFO] Loading PDS to ES data type mapping from e:\opt\harvest-3.9.0\elastic\data-dic-types.cfg
[INFO] Loading PDS to ES data type mapping from e:\opt\harvest-3.9.0\elastic\data-dic-types.cfg
[INFO] Processing bundle directory \\[localGeoPath]\data\lro\lro-l-dlre-2-edr-v1
[INFO] Processing bundle \\[localGeoPath]\data\lro\lro-l-dlre-2-edr-v1\bundle_diviner_raw.xml
[WARN] Bundle urn:nasa:pds:lro_diviner_raw::1.0 already registered. Skipping.
[WARN] No collections found in \\[localGeoPath]\data\lro\lro-l-dlre-2-edr-v1
[INFO] Processing bundle directory \\[localGeoPath]\data\lro\lro-l-dlre-4-rdr-v1
[INFO] Processing bundle \\[localGeoPath]\data\lro\lro-l-dlre-4-rdr-v1\bundle_diviner_calibrated.xml
[WARN] Bundle urn:nasa:pds:lro_diviner_calibrated::1.0 already registered. Skipping.
[WARN] No collections found in \\[localGeoPath]\data\lro\lro-l-dlre-4-rdr-v1
[SUMMARY] Summary:
[SUMMARY] Skipped files: 2
[SUMMARY] Loaded files: 0
[SUMMARY] Failed files: 0
[SUMMARY] Package ID: 64fb9511-78d0-4df3-8299-f24622cd60cc

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 📚 Version of Software Used

Windows Server 2019 (VM)

Harvest version: 3.9.0-SNAPSHOT
Build time: 2023-11-28T23:35:01Z

### 🩺 Test Data / Additional context

Email me if you would like the log file.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@scholes-ds to clarify, is harvesting at least finding these files and skipping them? Or is the software missing them altogether?

also, when you say updated, I am assuming the collections been versioned? or just updated?

**Comment by jordanpadams** [comment]
Confirmed with user this is no longer an issue
