### ISSUE TITLE
Add schema reference to all examples to take advantage of new schema

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#156]
### 💡 Description

Per https://github.com/NASA-PDS/harvest/pull/146, we have a new schema to describe the Harvest config. We need to add this to the XML declaration so a user can more easily update and validate their values are accurate.

**Comment by al-niessner** [comment]
@jordanpadams 

Is this what you had in mind?

```
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
      xsi:schemaLocation="https://github.com/NASA-PDS/harvest/blob/main/src/main/resources/conf/configuration.xsd"
```

**Comment by jordanpadams** [comment]
@al-niessner works for me!
