### ISSUE TITLE
As a user, I want to include my organization name in the harvest metadata (`ops:Harvest_Info.ops:node_name`)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#187]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can search by my node data and effectively track who loaded the data in Harvest.

### 📖 Additional Details

Value set:
```
  *     PDS_ATM  - Planetary Data System: Atmospheres Node
  *     PDS_ENG  - Planetary Data System: Engineering Node
  *     PDS_GEO  - Planetary Data System: Geosciences Node
  *     PDS_IMG  - Planetary Data System: Imaging Node
  *     PDS_NAIF - Planetary Data System: NAIF Node
  *     PDS_PPI  - Planetary Data System: Planetary Plasma Interactions Node
  *     PDS_RMS  - Planetary Data System: Rings Node
  *     PDS_SBN  - Planetary Data System: Small Bodies Node
  *     PSA      - Planetary Science Archive
  *     JAXA     - Japan Aerospace Exploration Agency
  *     ISRO     - Indian Space Research Organisation
```

### Acceptance Criteria

**Given** data to be harvested by Engineering Node
**When I perform** a harvest of data
**Then I expect** the value of `ops:Harvest_Info.ops:node_name` to be set to `PDS_ENG`

**Given** data to be harvested by ESA's Planetary Science Archive
**When I perform** a harvest of data
**Then I expect** the value of `ops:Harvest_Info.ops:node_name` to be set to `PSA`

**Comment by al-niessner** [comment]
See comments in #186

**Comment by c-suh** [comment]
@tloubrieu-jpl and @al-niessner, did I do this correctly? Next time, kindly leave very obvious instructions/commands under "I&T" in the issue description for how to test this. What I pieced together:
1. from https://github.com/NASA-PDS/registry/issues/350#issuecomment-2873667081 (different issue, but relevant info)
> ...as an EN person. You can use harvest to do that (updating the node in the connection configuration file)
   I changed my harvest_config file to `  <nodeName>JAXA</nodeName>`
2. `% harvest -c harvest_config.xml`

I used registry-client both before and after this harvest upload/ingest to get all distinct values for `ops:Harvest_Info/ops:node_name`. The total hits count went up, but the distinct values didn't change from only PDS_ENG.

I also queried one of the specific LIDVIDs that I had just added, and it shows its ops:node_name is PDS_ENG.

So, either this test failed or I didn't change the value as the submitting node in the correct place. Which is it, please?

**Comment by jordanpadams** [comment]
@c-suh can you provide more details as to the data you tried to upload? Was this data already in the registry? If so, you will need to use the `-o` flag to overwrite.

Additionally, what was the registry-client query you attempted and the response?

**Comment by jordanpadams** [comment]
Also, for the instructions, I would prefer the acceptance criteria are improved in these cases, where possible. We may need additional details, but in many cases, the acceptance criteria are the test plan so they should be accurate.

**Comment by jordanpadams** [comment]
i just updated the acceptance criteria. let me know if that makes it any more clear?

**Comment by al-niessner** [comment]
`<nodeName>` is not longer used/exists. The `ops:node_name` is derived from the registry index you are using as the upload destination.

**Comment by jordanpadams** [comment]
@c-suh you need to modify `registry-index` value in your registry config.

**Comment by c-suh** [comment]
@al-niessner ah, I see that `<nodeName>` was indeed removed and that I was working off an older version of the harvest config file. Apologies.

@jordanpadams yes, thank you, the criteria (and how to go about testing this) is much more clear now. However, going off yesterday's conversation with Thomas, I need to belong to a certain group to be able to write to its registry/index, yes? If so, I can only write to the en-registry and do not have the means to adequately test this.

@tloubrieu-jpl, from [your comment here](https://github.com/NASA-PDS/registry/issues/350#issuecomment-2593762527), there is a test user account for the GEO node. However, our dev environment doesn't have the relevant registry. How should I proceed?
