### ISSUE TITLE
As a user, I don't want to insert a product which has been already inserted with the same lidvid

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#195]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data user.

### 💪 Motivation

...so that I don't introduce duplicates in the registry.

I want to check that wherever the product has been previously harvested, including by another node.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

This will require that a discipline node has read access to the other discipline node's indexes.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl were you able to see if we can give read access to all the indexes to all nodes ? We would keep write access only on the specific node indexes. Thanks

**Comment by al-niessner** [comment]
#213
