### ISSUE TITLE
harvest by default overwrites all products

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#213]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

From @scholes-ds 

When a bundle is loaded twice without -overwrite option, the second time oall the product are overwritten.

### 🕵️ Expected behavior

I expected the default behavior to not overwrite existing products.

### 📜 To Reproduce

1. load a bundle with command `harvest -c urn-nasa-pds-relab.xml`
2. update the archive status
3.load the bundle again
4. the archive status a re-initialized to "staged"

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

I think we have been doing this all along. harvest only uses the bulk interface. It has always use the "index" on the bulk command when adding a document. Interestingly, this means that if it exists, then overwrite it otherwise create it and has been this way since opensearch 1.0

**Comment by jordanpadams** [comment]
@al-niessner hmmm. did we ever do some filtering to prune down what actually makes it into the bulk upload?

**Comment by jordanpadams** [comment]
I feel like we definitely had a "skipped" log message, which skipped products.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Code blame claims has not changed in two years (specifically lines 26-43):
https://github.com/NASA-PDS/registry-common/blame/main/src/main/java/gov/nasa/pds/registry/common/util/json/NJsonDocUtils.java

**Comment by jordanpadams** [comment]
@al-niessner not sure how/where the "skipped" functionality was implemented in the past, but it was at least logging it as such from the very beginning. are we saying we have been logging it as skipped, but then not actually skipping anything?

**Comment by al-niessner** [comment]
@jordanpadams 

Sorry I had found it and created PR that fixes it but typed the issue wrong in the PR so it did not connect.
