### ISSUE TITLE
The productFilter/excludeClass option in the harvest job configuration does not work

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#214]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Raised by @plawton-umd :

The <productFilter>  <excludeClass> combination appears to no longer 
work.  Are there any settings I can use in the configuration file to exclude
a Class or directory please?

### 🕵️ Expected behavior

I expected it to work by excluding a given class of products, e.g. Product_Collection.

### 📚 Version of Software Used

harvest 4.0.3

**Comment by jordanpadams** [comment]
closing bug since the requirement was missing: #218
