### ISSUE TITLE
Could not parse date in yyyy-MM-ddZ format

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/harvest#29]
Some OREX labels (collections) have <start_date_time> in  "yyyy-MM-ddZ" format (e.g., 2016-09-08Z) which Harvest could not parse. For example, OREX/OCAMS/data_calibrated/collection_ocams_data_calibrated.xml collection.

It doesn't look like a valid date. A date without time, but with a timezone considered invalid, at least in Java. Timezone usually makes sense if there is both a date and a time.

Need confirmation that "2016-09-08Z" is valid or not in PDS labels.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams will send @tdddblog  the regex of the supported date format so that Eugene can fix it.

**Comment by jordanpadams** [comment]
@tdddblog all possible datetime formats in PDS4:
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.5%C2%A0%C2%A0class_pds_ascii_date
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.6%C2%A0%C2%A0class_pds_ascii_date_doy
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.7%C2%A0%C2%A0class_pds_ascii_date_time
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.8%C2%A0%C2%A0class_pds_ascii_date_time_doy
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.9%C2%A0%C2%A0class_pds_ascii_date_time_doy_utc
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.10%C2%A0%C2%A0class_pds_ascii_date_time_utc
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.11%C2%A0%C2%A0class_pds_ascii_date_time_ymd
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.12%C2%A0%C2%A0class_pds_ascii_date_time_ymd_utc
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#23.13%C2%A0%C2%A0class_pds_ascii_date_ymd
