### ISSUE TITLE
Add default configuration

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#37]
The package should contain a default configuration which comply with following contraints:
1) should work as-is on example data given in pds-registry-app package
2) should contain every possible configuration (especially those needed for demo as described on https://github.com/NASA-PDS/pds-registry-app/issues/107) **commented out**

**Comment by tdddblog** [comment]
There are multiple issues with pds-registry-app package. It seems like nobody tested it.
- The test data is invalid. Some files are missing lid / vid. I don't know if it is done on purpose to check error handling.
- Test data only has label files. Data products are missing.
- Both harvest and registry manager don't have batch scripts for windows.

**Comment by tdddblog** [comment]
After installation, example configurations are available in ".../harvest-3.3.1/conf/examples/" folder.
