### ISSUE TITLE
Fix bug where ingested product start_date_time is off by 12 hours

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#4]
This may be harvest's problem, but it may be elsewhere. Maybe it goes away without the registry, if that's still a thing.

I just ingested/indexed some OREX bundles, and the start_date_times of the search result and the original input file differ, as circled in orex.jpg. Note that the output is 12 hours behind the input .xml file. In insight.jpg, the output is 12 hours ahead of the input file. Also odd is that stop_date_time is correct in insight.jpg.

See issue on internal Github for more details.

https://github.jpl.nasa.gov/PDSEN/harvest/issues/3#issue-205493

**Comment by jordanpadams** [comment]
@rchenatjpl this is also still an open issue.

**Comment by tdddblog** [comment]
Fixed by #24
