### ISSUE TITLE
error identified with too many open files when ingesting InSight data

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#43]
**Describe the bug**
While running harvest on IMG, a message too many files open came.

**To Reproduce**
See Kevin 

**Expected behavior**
Should work

**Comment by tloubrieu-jpl** [comment]
@tdddblog was not able to reproduce but sent a debug version of harvest to Kevin to understand what the issue is.

**Comment by tdddblog** [comment]
Could not reproduce on my setup. Built custom version of Harvest with more debug messages for Kevin to troubleshoot.

**Comment by jordanpadams** [comment]
closing as fixed since we have not heard back from customer that this is still a problem

**Comment by kgrimes2** [comment]
@tloubrieu-jpl @tdddblog Sorry about the delay on this response, I finished running Harvest against our InSight holdings. Here was the stdout:

```
[pdsadmin@pdsimg-int1 harvest_testing]$ harvest-3.3.3/bin/harvest -c $PWD/config.xml -f json -o $PWD/out -l $PWD/harvest.log -v 0
[INFO] Output directory: /home/pdsadmin/kgrimes/harvest_testing/out
[INFO] Output format: json
[INFO] Reading configuration from /home/pdsadmin/kgrimes/harvest_testing/config.xml
******************** 10
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/data/collection_data_6.0.xml
******************** 18
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/data/collection_data_7.0.xml
******************** 19
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/data/collection_data_5.0.xml
******************** 20
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/data/collection_data_8.0.xml
******************** 18
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/data/collection_data.xml
******************** 1616
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/browse/collection_browse_8.0.xml
******************** 1610
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/browse/collection_browse_6.0.xml
******************** 1611
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/browse/collection_browse_5.0.xml
******************** 3833
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/browse/collection_browse.xml
******************** 3834
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/browse/collection_browse_7.0.xml
******************** 3835
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/document/collection_document.xml
******************** 3840
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/calibration/collection_calibration.xml
******************** 3841
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/xml_schema/collection_xml_schema.xml
******************** 3841
[INFO] Processing file /mnt/pdsdata/nsyt/public/insight_cameras/miscellaneous/collection_miscellaneous.xml
******************** 3844
[INFO] Summary:
[INFO] Skipped files: 0
[INFO] Processed files: 14
[INFO] File counts by type:
[INFO]   Product_Collection: 14
[INFO] Package ID: da83c115-493d-475e-badc-1646a7847a41
******************** 3849
```

This actually succeeded, and I'm realizing that's probably because I had it scanning the wrong collections... so I'm kicking it off _again_. Will try to get back to you more quickly this time 🙂

Not sure if the above it helpful to you at all.

**Comment by kgrimes2** [comment]
@tdddblog Going back to the Slack thread, you mentioned that those numbers being printed in-between the `[INFO]` lines are the number of open files, and that it shouldn't go over 11 or so. So I think this demonstrates the problem.. even though in this case it didn't cause Harvest to crash because I ran against the wrong collections.

**Comment by tdddblog** [comment]
@kgrimes2 In the attached config you have the following product filter
```
   <productFilter>
      <include>Product_Collection</include>
      <include>Product_Context</include>
    </productFilter>
```
That's why observational products are not extracted.

When I have time I'll try to test latest Harvest with your data. In more recent versions of Harvest we use core Java APIs instead of Apache commons library to crawl filesystem.

**Comment by kgrimes2** [comment]
Cool, thanks @tdddblog. If you wanna drop me a more recent version of Harvest I can kick it off, and make sure I update the config to remove the product filter.

**Comment by jordanpadams** [comment]
@kgrimes2 you can download the latest registry-app package here: https://nasa-pds.github.io/pds-registry-app/

**Comment by kgrimes2** [comment]
I updated Harvest to the latest version, and ran it with OpenJDK 11. The issue appears to be resolved, as I'm roughly 40k files through our InSight holdings and the number of open files hasn't exceeded 26 (before it was in the thousands).

Thanks for your help, @tdddblog!!

**Comment by kgrimes2** [comment]
FYI: harvest completed running on our entire InSight bundle over the weekend, and fluctuated between 26 and 27 open files the whole time. Think we're in good shape. Thanks again for working this!

**Comment by jordanpadams** [comment]
@kgrimes2 do you by chance have the number of files and the time it took to complete? It would be good to have some metrics captured for this.

**Comment by kgrimes2** [comment]
@jordanpadams Sure do:

```
[SUMMARY] Summary:
[SUMMARY] Skipped files: 0
[SUMMARY] Processed files: 421903
[SUMMARY] File counts by type:
[SUMMARY]   Product_Ancillary: 34
[SUMMARY]   Product_Browse: 162046
[SUMMARY]   Product_Bundle: 5
[SUMMARY]   Product_Collection: 14
[SUMMARY]   Product_Document: 25
[SUMMARY]   Product_File_Text: 197
[SUMMARY]   Product_Observational: 259572
[SUMMARY]   Product_XML_Schema: 10
[SUMMARY] Package ID: ac84f8ff-00eb-4715-9dff-bb12c5c464e3

real    1590m18.748s
user    152m4.563s
sys     62m53.452s
```
