### ISSUE TITLE
Update harvest to ingest context metadata from context products and ignore information in labels

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#5]
**Is your feature request related to a problem? Please describe.**
Current implementation reads values like investigation name and target name from the labels, but it should really grab this information from the context product. Similar to how validate checks this information, harvest should ignore those values and just pull the data from the context information.

**Comment by rchenatjpl** [comment]
I'm testing #4 now. Is this one solved?  I could easily imagine that search would handle this.

**Comment by jordanpadams** [comment]
@rchenatjpl no. this is still an open issue.

**Comment by rchenatjpl** [comment]
Before we work on this, we may want to scrub the context products for crummy names, like spacecraft VIKING ORBITER 1, which I assume is weak because it's all caps. However, the name and the type for any context object may someday change, especially for old objects.

**Comment by jordanpadams** [comment]
closing as wontfix. will handle this at API level
