### ISSUE TITLE
harvest ingest is not creating all product_lidvid as an array

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/harvest#50]
## 🐛 Describe the bug
Loaded elasticsearch (ES) with latest pds-registry-app using fresh download of harvest-3.5.0-SNAPSHOT (has date of download May 12 not creation). Modifying registry-service-app to use the registry-ref index and found that for this collection id

urn:nasa:pds:izenberg_pdart14_meap:data_tnmap::1.0::P1

"product_lidvid" : "urn:nasa:pds:izenberg_pdart14_meap:data_tnmap:thermal_neutron_map::1.0",

## 📜 To Reproduce
1. create and fill ES database using README.md instructions for docker
2. in browser goto http://localhost:9200/registry-refs/_search?pretty
3. Scroll down to "id": "urn:nasa:pds:izenberg_pdart14_meap:data_tnmap::1.0::P1"
4. See error a couple of lines below

## 🕵️ Expected behavior
Verified with @jordanpadams and @tloubrieu-jpl that the design desirement is that it look like:

"product_lidvid" : ["urn:nasa:pds:izenberg_pdart14_meap:data_tnmap:thermal_neutron_map::1.0"],

##  🏞Screenshots
![not-an-array](https://user-images.githubusercontent.com/1130658/118158618-e155d400-b3d0-11eb-81a0-4789de6ec698.png)

---

** :unicorn: Applicable requirements**

**Comment by tloubrieu-jpl** [comment]
@jordanpadams yes this is the type of mismatch that I was thinking of. I need to check in details.

**Comment by tdddblog** [comment]
Fixed. See https://github.com/NASA-PDS/harvest/pull/51
