### ISSUE TITLE
Combine ingestion components under new ingest repo

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#68]
## Engineering Details
My two cents: we rename harvest repo site to ingest, and combine all these components under there.

Here are the components I think we should combine: harvest, registry-mgr-elastic, big-data-*, supplementer, pds-registry-common

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I would refer to the spreadsheet for the organizarion of new repository: https://docs.google.com/spreadsheets/d/1jTP_21jIW9wLnncdAKZgeIESf5eI4HSHQCAe3mVVG-E/edit#gid=0

The cell high-lighted in brown would be the new repositories. 

I though of merging:
harvest, registry-mgr-elastic, supplementer, pds-registry-common on one side
and keep the big-data-* as single repository.

The reason for that is that I would like to target to have a single docker image per repository.

The orchestration of the docker images (docker-compose, terraform) would be done in the application repository (in this case 'registry'). This is maybe a bit too dogmatic but I would like us to have a driver for the granularity of repository and that might also help with the CICD.

**Comment by jordanpadams** [comment]
per above closing as wontfix
