### ISSUE TITLE
harvest tool removed all json files on error 

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/harvest#73]
## 🐛 Describe the bug identified during I&T
This is related to test for  [Close all open files on error #67 ](https://github.com/NASA-PDS/harvest/pull/67)

The normal test file generates json files in /tmp/harvest/output, but after adding the suggested bad xml file with content "kdfdfkdjf;'dkflkf", harvest outputs the expected error message. but the files in /tmp/harvest/output are all empty.

## 🥼 Related Test Case(s)
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1013928

## 🔁 Related issues

https://github.com/NASA-PDS/pds-registry-app/issues/205

---

### 📜 To Reproduce
see https://github.com/NASA-PDS/harvest/pull/67

### 📚 Version of Software Used
Harvest version: 3.5.2-SNAPSHOT
Build time: 2021-12-10T07:51:23Z

###  🏞Screenshots
before adding x.xml
![image](https://user-images.githubusercontent.com/4574373/146817182-f3b19044-34ec-427a-9446-baa6e9572931.png)
after adding x.xml
![image](https://user-images.githubusercontent.com/4574373/146817266-2828a1a9-f666-493e-a915-bb970b243232.png)

### 🖥 System Info

---

**Comment by tdddblog** [comment]
@gxtchen Can you provide logs? If "bad" file is first in the list of processed files, you would see empty output files.

**Comment by gxtchen** [comment]
@tdddblog You were right, my operating system always process the x.xml file first. I confirm it is working as expected after renaming it to a longer file name.
