### ISSUE TITLE
Error ingesting an XML boolean with values of 0/1

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#78]
## 🐛 Describe the bug

Valid XML boolean value not being converted to the ES boolean field type

## 📜 To Reproduce
```
bash-4.2$ registry-manager load-data -es https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com:443 \-auth /home/itrejo/es-auth.cfg -dir out & 
[1] 17567
bash-4.2$ [INFO] Registry URL: https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com:443
[INFO] Registry index: registry
[INFO] Loading PDS to ES data type mapping from /home/atmos4/PDS/pds-registry-app-1.0.3/registry-manager-4.3.1/elastic/data-dic-types.cfg
[INFO] Updating LDDs from /export/atmos4/PDS/harvest/out/missing_xsds.txt
[INFO] Updating 'pds' LDD. Schema location: https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1G00.xsd
jo[INFO] This LDD already loaded.
[INFO] Updating 'mars2020' LDD. Schema location: https://pds.nasa.gov/pds4/mission/mars2020/v1/PDS4_MARS2020_1G00_1000.xsd
[INFO] This LDD already loaded.
[INFO] Updating schema with fields from /export/atmos4/PDS/harvest/out/missing_fields.txt
[INFO] Updated 226 fields
[INFO] Loading ES data file: /export/atmos4/PDS/harvest/out/registry-docs.json
[ERROR] failed to parse field [mars2020:Algorithm_Parameter_Table_Values/mars2020:persistence_en] of type [boolean] in document with id 'urn:nasa:pds:mars2020_moxie:data_derived:ox__0004_0667297777ddr___0010052moxi00101p01::1.0'. Preview of field's value: '0'
[ERROR] Could not load data.
```

## 🕵️ Expected behavior

Ingests successfully as a boolean field type.

## 📚 Version of Software Used

SNAPSHOT as of https://github.com/NASA-PDS/harvest/commit/6e68b5c49ae214aa48686e62e598f199fc97415e

## 🩺 Test Data / Additional context

https://atmos.nmsu.edu/PDS/data/PDS4/Mars2020/moxie_bundle/data_derived/0004/OX__0004_0667297777DDR___0010052moxi00101P01.xml

## 🖥 System Info

---

## ⚙️ Engineering Details
PDS4 `ASCII_Boolean` maps to `xs:boolean`, which, per [these docs](https://www.oreilly.com/library/view/xml-schema/0596002521/re58.html) can be one of `(0, 1, true, false)`.

After poking around at how to handle this with ES, it sounds like if we translate the 0,1,true,false from the XML to JSON, it will automatically turn those into true,false (I think?). But since we don't really pay attention to which field is a boolean or not, we don't do this translation.

Possible solutions:
* Translate these fields from the client
* Add a script to the field type in ES to translate on the service ingestion side

As an additional note, looks like this was supposed to be handled by ElasticSearch a while ago, but there was a regression at some point? https://github.com/elastic/elasticsearch/issues/26

**Comment by tloubrieu-jpl** [comment]
This will need to update harvest so that it updates the elasticSearch schema. This is the most "easy" fix for now. This will also solve some issues with the Date date types.

**Comment by tloubrieu-jpl** [comment]
The registry-manager data-load function will be now available from harvest (after this ticket is done).

Note that this will break the registry docker-compose.

**Comment by tloubrieu-jpl** [comment]
harvest/registry-mgr is updated.

The scalable harvest components still need updates as well as documentation.

**Comment by jordanpadams** [comment]
closed per PRs above
