### ISSUE TITLE
Error ingesting a datetime field pds:Time_Coordinates/pds:stop_date_time

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#81]
## 📜 To Reproduce
```
bash-4.2$ registry-manager load-data -es [https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com:443](https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com/) -auth /home/itrejo/es-auth.cfg -dir /home/atmos4/PDS/harvest/out &
[1] 45180
bash-4.2$ [INFO] Registry URL: [https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com:443](https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com/)
[INFO] Registry index: registry
[INFO] Loading PDS to ES data type mapping from /home/atmos4/PDS/pds-registry-app-1.0.3/registry-manager-4.3.1/elastic/data-dic-types.cfg
[INFO] Updating LDDs from /home/atmos4/PDS/harvest/out/missing_xsds.txt
[INFO] Updating 'pds' LDD. Schema location: https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1G00.xsd
[INFO] This LDD already loaded.
[INFO] Updating 'pds' LDD. Schema location: http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1G00.xsd
[INFO] This LDD already loaded.
[INFO] Updating schema with fields from /home/atmos4/PDS/harvest/out/missing_fields.txt
[INFO] Updated 1 fields
[INFO] Loading ES data file: /home/atmos4/PDS/harvest/out/registry-docs.json
[INFO] Loaded 500 document(s)
[INFO] Loaded 1000 document(s)
[INFO] Loaded 1500 document(s)
[INFO] Loaded 2000 document(s)
[INFO] Loaded 2500 document(s)
[INFO] Loaded 3000 document(s)
[INFO] Loaded 3500 document(s)
[INFO] Loaded 4000 document(s)
[ERROR] failed to parse field [pds:Time_Coordinates/pds:stop_date_time] of type [date] in document with id 'urn:nasa:pds:eldorado_nv_dd_ptv:data_derived:f_p10_2_data-133::1.0'. Preview of field's value: '2012-06-31T02:22:47.956Z'
[ERROR] Could not load data.
```

## 🕵️ Expected behavior

Ingests the data successfully or throws error but still ingests the data products.

## 📚 Version of Software Used

Latest snapshot.

## 🩺 Test Data / Additional context

https://atmos.nmsu.edu/PDS/data/PDS4/eldorado_nv_dd_ptv/data_derived/Location_F/f_p10_2_data-133.xml
https://atmos.nmsu.edu/PDS/data/PDS4/eldorado_nv_dd_ptv/data_derived/Location_F/f_p10_2_data-133.csv

---

## ⚙️ Engineering Details
Creating additional ticket to overall handle errors more gracefully

**Comment by tdddblog** [comment]
@jordanpadams The date is invalid. June only has 30 days, but the date string is "2012-06-31..."

**Comment by jordanpadams** [comment]
😆 wow! definitely did not catch that, and neither did the PDS4 Information Model. Yikes!

**Comment by jordanpadams** [comment]
thanks @tdddblog for the quick turnaround on this! we will need to fix this in the PDS4 Information Model, but we should still work on https://github.com/NASA-PDS/pds-registry-app/issues/251 to figure out a way to get this data into the Registry, even if it is just a very very minimal subset of metadata (e.g. the LIDVID for the product and maybe some new field to capture an error message?)
