### ISSUE TITLE
Incorrect "lidvid" and  "_id" fields are ingested (trailing zeros are truncated)

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/harvest#90]
## 🐛 Describe the bug
If a `version_id` field has trailing zeros, for example `1.10`, the value is truncated to `1.1` when `lidvid` and `_id` fields are generated.
For example `logical_identifier` = `urn:nasa:pds:maven.anc`, `version_id` = `1.10`. Generated `lidvid` and `_id` = `urn:nasa:pds:maven.anc::1.1`

## 📜 To Reproduce
1. Create a label with the `version_id` field containing trailing zeros, for example, `1.10`
2. Run Harvest to Ingest the label.
3. Check the `lidvid` and `_id` fields in OpenSearch / Elasticsearch.

## 🕵️ Expected behavior
`version_id` should not be truncated.

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl 
Need to create point build for this bug fix
