### ISSUE TITLE
harvest Incorrect "lidvid" and "_id" fields are ingested

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/harvest#95]
## 🐛 Describe the bug identified during I&T
I changed the version_id from my previous testing to 2.0. 1.10.0 and 1.20, but no matter what I set it to, when I query http://localhost:9200/registry/_search?q=* I always get back urn:nasa:pds:lab_shocked_feldspars:data::1.0, you can see my test steps and test results here: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3869751&group_by=cases:section_id&group_order=asc&group_id=90426

### 🖥 System Info
Harvest version: 3.7.0-SNAPSHOT
Build time: 2022-05-27T15:39:34Z
---

## Related issue
Bug raised while testing
https://github.com/nasa-pds/harvest/issues/90

**Comment by tloubrieu-jpl** [comment]
@gxtchen I removed the section 'Related requirements' and replaced it with 'Related issue' since the section 'Related requirements' is processed to identify/report on the requirements impacted by development work.

**Comment by tloubrieu-jpl** [comment]
At last @gxtchen I don't understand that you deleted the registry and was still able to see version 1.0.

Have you checked that the request http://localhost:9200/registry/_search?q=* returns nothing if you run it before step 5 of your test sequence ?

It feels like you might have multiple registries deployed at the same time.

**Comment by tloubrieu-jpl** [comment]
@gxtchen do you still have this issue ?

**Comment by gxtchen** [comment]
I retest this ticket again with 3 different tests, 2 passed and 1 fail. It was my bad not checking the cfg.xml file, it was still pointing to the path that I copy the test case from. After fixing the path, all 3 tests passed.

**Comment by tloubrieu-jpl** [comment]
Thanks @gxtchen
